base: &base
  encoding: 'utf8'
  adapter: 'postgresql'
  pool: 5
  username: 'tom'
  host: 'localhost'
development:
  database: 'mud_development'
  <<: *base
test: &test
  database: 'mud_test'
  <<: *base
cucumber:
  <<: *test

